#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
#bspc config window_gap          12
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bcpc bottom_padding              0
bcpc left_padding                0
bcpc right_padding 							 0
bcpc single_monocle              false
bcpc click_to_focus              false
bcpc focus_by_distance           true
bcpc paddingless_monocle  	  	 true
bcpc ignore_ewmh_focus 		  		 true
bcpc history_aware_focus         true
bcpc remove_disabled_monitors    true
bcpc merge_overlapping_monitors  true

#bspc config normal_border_color	"#0a0324"
#bspc config focused_border_color "#FF2079"
bspc config active_border_color "#474f54"
bspc config focused_border_color "#474f54"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_motion_interval   5
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc rule -a tdrop sticky=on state='floating' focus=on
bspc rule -a discord state='pseudo_tiled' desktop='^9'
#bspc rule -a firefox desktop='^2'
bspc rule -a feh state='floating' rectangle='966x543+0+0' center='true'
bspc rule -a Spotify state='pseudo_tiled' desktop='^10' center='true' follow='true'
bspc rule -a mpv state='floating' center='true'
bspc rule -a megasync='floating' center='true'
bspc rule -a Pavucontrol state='floating' center='true'
bspc rule -a Nitrogen state='floating' center='true'
bspc rule -a Screenkey manage=off


setxkbmap us &
xrandr --output eDP-1 --mode 1920x1080 --rate 60
#lxsession &
xsetroot -cursor_name left_ptr &
sxhkd &
$HOME/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf -fb &
#nitrogen --restore &
nitrogen --set-zoom-fill ~/.config/wallpaper.png
dunst &
libinput-gestures-setup start &
mpd &
pidof redshift || redshift -c ~/.config/redshift/redshift.conf &
