#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color	"#0a0324"
bspc config focused_border_color "#FF2079"

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_motion_interval   5
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc rule -a tdrop sticky=on state=floating focus=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Nitrogen state=floating center=true
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd &
$HOME/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf -fb &
nitrogen --restore &
dunst &
